2025-10-26 21:47:21.61
285d28ce
User
ERROR: Exception in ASGI application
2025-10-26 21:47:21.61
285d28ce
User
Traceback (most recent call last):
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
2025-10-26 21:47:21.61
285d28ce
User
result = await app( # type: ignore[func-returns-value]
2025-10-26 21:47:21.61
285d28ce
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-10-26 21:47:21.61
285d28ce
User
return await self.app(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/applications.py", line 1133, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await super().__call__(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await self.middleware_stack(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
2025-10-26 21:47:21.61
285d28ce
User
raise exc
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await self.app(scope, receive, _send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await self.simple_response(scope, receive, send, request_headers=headers)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
2025-10-26 21:47:21.61
285d28ce
User
await self.app(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-10-26 21:47:21.61
285d28ce
User
raise exc
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-10-26 21:47:21.61
285d28ce
User
await app(scope, receive, sender)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await self.app(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
2025-10-26 21:47:21.61
285d28ce
User
await self.middleware_stack(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
2025-10-26 21:47:21.61
285d28ce
User
await route.handle(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
2025-10-26 21:47:21.61
285d28ce
User
await self.app(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/routing.py", line 123, in app
2025-10-26 21:47:21.61
285d28ce
User
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-10-26 21:47:21.61
285d28ce
User
raise exc
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-10-26 21:47:21.61
285d28ce
User
await app(scope, receive, sender)
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/routing.py", line 109, in app
2025-10-26 21:47:21.61
285d28ce
User
response = await f(request)
2025-10-26 21:47:21.61
285d28ce
User
^^^^^^^^^^^^^^^^
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/routing.py", line 389, in app
2025-10-26 21:47:21.61
285d28ce
User
raw_response = await run_endpoint_function(
2025-10-26 21:47:21.61
285d28ce
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/fastapi/routing.py", line 288, in run_endpoint_function
2025-10-26 21:47:21.61
285d28ce
User
return await dependant.call(**values)
2025-10-26 21:47:21.61
285d28ce
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 21:47:21.61
285d28ce
User
File "/home/runner/workspace/routers/matches.py", line 970, in update_match
